### ISSUE TITLE
Custom Video Shortcode

### ISSUE THREAD

**Issue by cjtheham** [cjtheham/hugo-theme-readable#1]
With the introduction of v1.0.1 of readable.css, a new feature has been introduced:

`<video> elements are now treated the same way as <img> elements.`

Somehow the shortcode for video embeds needs to be updated to wrap everything in a figure and caption in order to have it render properly.

https://gohugo.io/content-management/shortcodes/#vimeo

**Comment by benjaminbhollon** [comment]
I'll also note, while using a <figure> is ideal and best practice, both <img> and <video> will still be sized properly when direct children of <body>, <article>, or <main> elements. So if that's easier, you're golden.

The specific effects are:

```
max-width: 100%
margin: var(--one-line) 0;
```

**Comment by benjaminbhollon** [comment]
Oh my, all of my tags just got removed. Let me try that again. :man_facepalming:

**Comment by benjaminbhollon** [comment]
I'll also note, while using a `<figure>` is ideal and best practice, both `<img>` and `<video>` will still be sized properly when direct children of `<body>`, `<article>`, or `<main>` elements. So if that's easier, you're golden.

The specific effects are:

```
max-width: 100%
margin: var(--one-line) 0;
```

**Comment by benjaminbhollon** [comment]
That worked much better. :joy:

**Comment by cjtheham** [comment]
Ahhhh. This explains an issue I ran into the other day. `img` wasn't a direct child of body but a div instead, so maybe I'm better off wrapping my posts in `<article>` tags overall no matter what...

But, I do like my best practices! So if I can figure out these video shortcodes then this will be added. 

Thanks @benjaminbhollon!

**Comment by benjaminbhollon** [comment]
That's generally what I'd do; always wrap the post content in `<article>`. Main content, I wrap in `<main>`.

Here's the specific selector, if it helps: `:is(body, article, main, figure) > :is(img, video):not(.exclude)`.

**Comment by rluetzner** [comment]
Incidentally, this is already part of #6 .

I've wrapped the `{{ .Content }}` (i.e. the Markdown posts) inside an `<article>` tag to support `<aside>`.

If #6 gets merged, this should also be resolved.

**Comment by benjaminbhollon** [comment]
Assuming the `<video>` ends up a direct child of the `<article>`, yes. It might be safest to figure out how to put it in a `<figure>` anyway, though that doesn't necessarily require a caption.

**Comment by rluetzner** [comment]
I'd assume that any `<video>` is part of a Markdown post someone created. In that case it would always be inside an `<article>` tag (with #6 ).

However, why not both? Better safe than sorry. Putting it inside a `<figure>` tag should be trivial. I can take a look at that.

I actually wrote a `<video>` shortcode for my website already, but never published the article using it. Mine connects to https://yewtu.be (an Invidious instance, where Invidious is a privacy friendly YouTube wrapper). It should be easy to adapt and extend.

**Comment by benjaminbhollon** [comment]
Well, note that it's not just being inside an `<article>`; it has to be a *direct* child. Same goes for `<figure>`.

**Comment by benjaminbhollon** [comment]
If that gets too tricky for implementation, I can consider extending the selector in readable.css. I was mostly trying to be conservative with what it was matching.

**Comment by rluetzner** [comment]
> Well, note that it's not just being inside an `<article>`; it has to be a direct child. Same goes for `<figure>`.

I don't think that'll be an issue. 🙂 For now I see no reason to extend the CSS.
