### ISSUE TITLE
Update to the latest version of readable.css

### ISSUE THREAD

**Issue by rluetzner** [cjtheham/hugo-theme-readable#12]
v1.1.0 has been released: https://codeberg.org/Freedom-to-Write/readable.css/releases

@cjtheham , can you describe a bit how you would go about updating the CSS?

If it's merely downloading the file from readable.css releases and putting in into this repo, this might be a good start for automation. I could look into scheduled GitHub actions that will check for newer releases, update the file and create a pull request to be reviewed. How does that sound? 🙂

**Comment by benjaminbhollon** [comment]
The easy way is that there are no breaking changes; just downloading the file and including it will work.

That said there is one visual change you may (or may not) wish to revert: by default, the navbar is no longer animated. To revert that, you can add `data-style="classy"` to the navbar. If you *don't* revert it, it may be worth removing the `<span>` elements surrounding each link, since those are only necessary for the `classy` navbar style, though they won't cause any issues with the default style.

Something that would be interesting to consider implementing with this release would be exposing some sort of setting to change the navbar style? Definitely not something that has to be implemented, of course.

**Comment by benjaminbhollon** [comment]
If you do automate, do make sure to check the major version number; that'll increase if there are major changes. That said, I currently have no plans of introducing breaking changes at any point in the future.

**Comment by benjaminbhollon** [comment]
Another possible help for the automation is that with semver (x.y.z), I will update z if the release is bugfix only (one that's a good candidate for automatic update), but if it has y updated, there are feature changes and it may be worth giving it special attention.

**Comment by rluetzner** [comment]
I did consider semantic versioning and possible breaking changes. However, at least as a first step, I'd have the automation create a pull request to be reviewed, rather than merging right to main.

That would give us a reminder that readable.css has been updated and would be a good time to review the release notes. Depending on that, I'd checkout the pull request and implement the necessary changes to support the latest version or merge it straight away.

I think this semi-automation will be sufficient for the release frequency of readable.css, at least right now. 🙂

**Comment by benjaminbhollon** [comment]
Having it as a PR is a good idea! :)

As per the release frequency, this isn't directly related but could be helpful for planning purposes: I'm not planning any more feature releases for a while. If bugs come up, I'll be fixing them, but I'm going to focus on getting Freedom to Write's next project launched for a little while.

**Comment by cjtheham** [comment]
So, for the last update to v1.0.1 all I did was upload the new file, update the version number attached to the `<link rel="stylesheet">` in `layouts/partials/head.html`, and made any necessary changes that the new version called for. See [this commit](https://github.com/cjtheham/hugo-theme-readable/commit/18e9cc19ea9b5a5b19430e3c4c27e9868ded2daf) for a reference. 

This is definitely a good candidate for automation, really like all the ideas you guys have proposed so far!

**Comment by benjaminbhollon** [comment]
Good job remembering to increment the version number in the stylesheet link! That's something I keep forgetting on my own sites.

…now that I'm using an SSG, it would probably be possible to automatically pull the most recent version. I should look into this.

**Comment by benjaminbhollon** [comment]
I've made a PR for this release: https://github.com/cjtheham/hugo-theme-readable/pull/13

This addresses a couple of quirks with this release in specific as well as updating the file. I've noted what those changes are in the PR.

For the sake of this issue's consideration of automation, note that with this PR I use both readable.css and readable.min.css, which would both need to be updated by automation. If you'd like, we can remove one or both, but I like having both to improve bandwidth usage (with the minified version) while still having a more readable version present for implementors of this template.

**Comment by rluetzner** [comment]
I can send in a PR later addressing the navbar style. It's really easy to do and I agree that it should be configurable in the config. 🙂

**Comment by cjtheham** [comment]
Closing this with the closing of #13.
