### ISSUE TITLE
Keep workflow to create PRs of releases from running for release candidates

### ISSUE THREAD

**Issue by benjaminbhollon** [cjtheham/hugo-theme-readable#20]
The title says it all, really. The workflow for creating PRs of new readable.css releases triggers for release candidates too.

I set the "Pre-Release" checkbox on Codeberg's end and append "-rc#" to the tag name, if it helps for the purposes of updating this.

**Comment by benjaminbhollon** [comment]
Understandable that this wasn't taken account since this is my first time ever making a release candidate. ;)

**Comment by rluetzner** [comment]
I'll have a look at it this evening. Maybe there's a way to improve the code anyway, now that I'm more familiar with `jq`. 🙂
